INSERT INTO "GenreList" VALUES(DEFAULT, 'Unknown', 'Nepoznato', 'Unbekannt');
INSERT INTO "GenreList" VALUES(DEFAULT, 'Other', 'Drugo', 'Andere');
INSERT INTO "GenreList" VALUES(DEFAULT, 'Prose', 'Proza', 'Prosa');
INSERT INTO "GenreList" VALUES(DEFAULT, 'Fiction', 'Fikcija', 'Fiktion');
INSERT INTO "GenreList" VALUES(DEFAULT, 'Science fiction', 'Znanstvena fantastika', 'Science-Fiction');
INSERT INTO "GenreList" VALUES(DEFAULT, 'Mystery fiction', 'Misterijska fantastika', 'Mystery');
INSERT INTO "GenreList" VALUES(DEFAULT, 'Crime fiction', 'Kriminalistički žanr', 'Krimi');
INSERT INTO "GenreList" VALUES(DEFAULT, 'Fantasy', 'Fantastika', 'Fantasy');
INSERT INTO "GenreList" VALUES(DEFAULT, 'Dictionary', 'Rječnik', 'Wörterbuch');
INSERT INTO "GenreList" VALUES(DEFAULT, 'Comedy', 'Komedija', 'Komödie');
INSERT INTO "GenreList" VALUES(DEFAULT, 'Memoir', 'Memoari', 'Memoiren');
INSERT INTO "GenreList" VALUES(DEFAULT, 'Thriller', 'Triler', 'Thriller');
INSERT INTO "GenreList" VALUES(DEFAULT, 'Novel', 'Roman', 'Roman');
INSERT INTO "GenreList" VALUES(DEFAULT, 'Novella', 'Novela', 'Novelle');
INSERT INTO "GenreList" VALUES(DEFAULT, 'Tale', 'Pripovijetka', 'Erzählung');
INSERT INTO "GenreList" VALUES(DEFAULT, 'Romance novel', 'Romantika', 'Liebesroman');
INSERT INTO "GenreList" VALUES(DEFAULT, 'Textbook', 'Udžbenik', 'Lehrbuch');
INSERT INTO "GenreList" VALUES(DEFAULT, 'Encyclopedia', 'Enciklopedija', 'Enzyklopädie');
INSERT INTO "GenreList" VALUES(DEFAULT, 'Journal', 'Časopis', 'Zeitschrift');
INSERT INTO "GenreList" VALUES(DEFAULT, 'Biography', 'Biografija', 'Biografie');
INSERT INTO "GenreList" VALUES(DEFAULT, 'Autobiography', 'Autobiografija', 'Autobiografie');
INSERT INTO "GenreList" VALUES(DEFAULT, 'Essay', 'Esej', 'Essay');
INSERT INTO "GenreList" VALUES(DEFAULT, 'Travel literature', 'Putopis', 'Reisebericht');
INSERT INTO "GenreList" VALUES(DEFAULT, 'Poetry', 'Poezija', 'Poesie');
INSERT INTO "GenreList" VALUES(DEFAULT, 'Collection of poems', 'Zbirka pjesama', 'Gedichtsammlung');
INSERT INTO "GenreList" VALUES(DEFAULT, 'Legend', 'Legenda', 'Legende');
INSERT INTO "GenreList" VALUES(DEFAULT, 'Myth', 'Mit', 'Mythos');
INSERT INTO "GenreList" VALUES(DEFAULT, 'Fairy tale', 'Bajka', 'Märchen');
INSERT INTO "GenreList" VALUES(DEFAULT, 'Fable', 'Basna', 'Fabel');
INSERT INTO "GenreList" VALUES(DEFAULT, 'Tragedy', 'Tragedija', 'Tragödie');
INSERT INTO "GenreList" VALUES(DEFAULT, 'Drama', 'Drama', 'Drama');
INSERT INTO "GenreList" VALUES(DEFAULT, 'Epic poetry', 'Ep', 'Epos');
