INSERT INTO "GenreList" VALUES(DEFAULT, 'Unknown', 'Nepoznato', 'Unbekannt');
INSERT INTO "GenreList" VALUES(DEFAULT, 'Other', 'Drugo', 'Andere');
INSERT INTO "GenreList" VALUES(DEFAULT, 'Comedy', 'Komedija', 'Komödie');
INSERT INTO "GenreList" VALUES(DEFAULT, 'Tragedy', 'Tragedija', 'Tragödie');
INSERT INTO "GenreList" VALUES(DEFAULT, 'Drama', 'Drama', 'Drama');
INSERT INTO "GenreList" VALUES(DEFAULT, 'Epic', 'Ep', 'Epos');
INSERT INTO "GenreList" VALUES(DEFAULT, 'Tale', 'Pripovijetka', 'Erzählung');
INSERT INTO "GenreList" VALUES(DEFAULT, 'Novella', 'Novela', 'Novelle');
INSERT INTO "GenreList" VALUES(DEFAULT, 'Novel', 'Roman', 'Roman');
INSERT INTO "GenreList" VALUES(DEFAULT, 'Collection of poems', 'Zbirka pjesama', 'Gedichtsammlung');
INSERT INTO "GenreList" VALUES(DEFAULT, 'Journal', 'Časopis', 'Zeitschrift');
INSERT INTO "GenreList" VALUES(DEFAULT, 'Essay', 'Esej', 'Essay');
INSERT INTO "GenreList" VALUES(DEFAULT, 'Travel literature', 'Putopis', 'Reisebericht');
INSERT INTO "GenreList" VALUES(DEFAULT, 'Fairytale', 'Bajka', 'Märchen');
INSERT INTO "GenreList" VALUES(DEFAULT, 'Fable', 'Basna', 'Fabel');
INSERT INTO "GenreList" VALUES(DEFAULT, 'Biography', 'Biografija', 'Biografie');
INSERT INTO "GenreList" VALUES(DEFAULT, 'Textbook', 'Udžbenik', 'Lehrbuch');
INSERT INTO "GenreList" VALUES(DEFAULT, 'Encyclopedia', 'Enciklopedija', 'Enzyklopädie');
